# Generated by Django 3.1.2 on 2020-10-06 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.TextField(blank=True, null=True)),
                ('grammar', models.IntegerField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('sentence', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subtitle', models.TextField(null=True)),
                ('author', models.TextField()),
                ('text', models.TextField()),
                ('reference', models.ManyToManyField(blank=True, related_name='words', to='nauta.Dictionary')),
            ],
        ),
        migrations.AddField(
            model_name='dictionary',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nauta.word'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Original', to='nauta.word'),
        ),
    ]
