# Generated by Django 3.1.2 on 2020-10-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nauta', '0002_text_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='grammar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
