# Generated by Django 3.1.2 on 2020-10-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nauta', '0003_auto_20201006_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='text',
            name='subtitle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
