# Generated by Django 3.1.2 on 2020-10-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nauta', '0004_auto_20201006_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typology', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Underline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nauta.grammar')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nauta.word')),
            ],
        ),
        migrations.AddField(
            model_name='grammar',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nauta.language'),
        ),
        migrations.AddField(
            model_name='text',
            name='underlines',
            field=models.ManyToManyField(blank=True, to='nauta.Underline'),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nauta.language'),
        ),
    ]
