# Generated by Django 3.1.2 on 2020-12-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nauta', '0008_auto_20201203_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='text',
            name='categories',
        ),
        migrations.AddField(
            model_name='text',
            name='categories',
            field=models.ManyToManyField(to='nauta.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
