# Generated by Django 3.1.2 on 2020-12-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nauta', '0010_textview'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
