# Generated by Django 3.1.2 on 2020-12-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nauta', '0012_auto_20201204_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='cat', to='nauta.Category'),
        ),
    ]
