# Generated by Django 3.1.2 on 2020-12-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nauta', '0014_auto_20201204_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='firstpost',
            new_name='firstchapter',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='copy',
            new_name='nocopy',
        ),
    ]
