# Generated by Django 3.1.7 on 2021-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nauta', '0016_text_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='categories',
            field=models.ManyToManyField(to='nauta.Category'),
        ),
    ]
