# Generated by Django 3.1.7 on 2021-07-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nauta', '0017_auto_20210311_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('trans', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='translations',
            field=models.ManyToManyField(blank=True, to='nauta.Translations'),
        ),
    ]
