# Generated by Django 3.2.7 on 2021-09-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nauta', '0019_transcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransComment',
        ),
    ]
